# Site settings
title:              Tabletop Cafe
email:              hello@tabletopcafe.com
description:        "Edmonton's premiere boardgame cafe."
url:                "http://tabletopcafe.com/"
# baseurl:            /main
baseurl: "/"

# File structure settings
#image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Sass
# sass:
#   sass_dir:          _scss
#   style:            :compressed
