# Site settings
title:              Table Top Cafe
email:              hello@tabletopcafe.com
description:        "Edmonton's premiere boardgame cafe."
url:                "https://tabletopcafe.com/"
# baseurl:            /main
baseurl: "/"

# File structure settings
#image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Sass
# sass:
#   sass_dir:          _scss
#   style:            :compressed
