---
title: Table Top Cafe
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@tabletopcafe.com
description: Edmonton's premiere boardgame cafe.
url: https://tabletopcafe.com/
baseurl: "/"
markdown: kramdown
permalink: pretty
