---
title: Table Top Cafe
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: brian@tabletopcafe.ca
description: Edmonton's premiere boardgame cafe.
url: https://tabletopcafe.ca/
baseurl: "/"
markdown: kramdown
permalink: pretty
